# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ghc.ui'
##
## Created by: Qt User Interface Compiler version 6.2.4
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractSpinBox, QApplication, QComboBox, QFrame,
    QLCDNumber, QLabel, QMainWindow, QSizePolicy,
    QSpinBox, QWidget)
import ghc_rc

class Ui_QFrmMain(object):
    def setupUi(self, QFrmMain):
        if not QFrmMain.objectName():
            QFrmMain.setObjectName(u"QFrmMain")
        QFrmMain.setWindowModality(Qt.NonModal)
        QFrmMain.resize(799, 239)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(QFrmMain.sizePolicy().hasHeightForWidth())
        QFrmMain.setSizePolicy(sizePolicy)
        QFrmMain.setCursor(QCursor(Qt.ArrowCursor))
        icon = QIcon()
        icon.addFile(u":/Resources/favicon", QSize(), QIcon.Normal, QIcon.Off)
        QFrmMain.setWindowIcon(icon)
        QFrmMain.setWindowOpacity(1.000000000000000)
        QFrmMain.setStyleSheet(u"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.actionSave = QAction(QFrmMain)
        self.actionSave.setObjectName(u"actionSave")
        self.actionLoad = QAction(QFrmMain)
        self.actionLoad.setObjectName(u"actionLoad")
        self.actionSettings = QAction(QFrmMain)
        self.actionSettings.setObjectName(u"actionSettings")
        self.centralwidget = QWidget(QFrmMain)
        self.centralwidget.setObjectName(u"centralwidget")
        self.cb_stage = QComboBox(self.centralwidget)
        self.cb_stage.addItem("")
        self.cb_stage.addItem("")
        self.cb_stage.addItem("")
        self.cb_stage.addItem("")
        self.cb_stage.addItem("")
        self.cb_stage.setObjectName(u"cb_stage")
        self.cb_stage.setEnabled(True)
        self.cb_stage.setGeometry(QRect(610, 45, 51, 41))
        font = QFont()
        font.setPointSize(20)
        self.cb_stage.setFont(font)
        self.cb_stage.setCursor(QCursor(Qt.PointingHandCursor))
        self.cb_stage.setLayoutDirection(Qt.LeftToRight)
        self.cb_stage.setAutoFillBackground(False)
        self.cb_stage.setMaxVisibleItems(5)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(610, 20, 50, 20))
        font1 = QFont()
        font1.setPointSize(11)
        font1.setBold(True)
        self.label.setFont(font1)
        self.label.setAlignment(Qt.AlignCenter)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(620, 155, 81, 21))
        font2 = QFont()
        font2.setPointSize(10)
        self.label_7.setFont(font2)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(620, 177, 81, 21))
        self.label_8.setFont(font2)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(620, 200, 81, 21))
        self.label_9.setFont(font2)
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setEnabled(False)
        self.frame.setGeometry(QRect(0, 0, 601, 240))
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy1)
        self.frame.setMaximumSize(QSize(16777215, 16777215))
        self.frame.setStyleSheet(u"border-image: url(:/Resources/bg) 0 0 0 0 stretch stretch;")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(720, 20, 50, 20))
        self.label_10.setFont(font1)
        self.label_10.setAlignment(Qt.AlignCenter)
        self.cb_v_2 = QComboBox(self.centralwidget)
        self.cb_v_2.addItem("")
        self.cb_v_2.addItem("")
        self.cb_v_2.addItem("")
        self.cb_v_2.addItem("")
        self.cb_v_2.addItem("")
        self.cb_v_2.addItem("")
        self.cb_v_2.addItem("")
        self.cb_v_2.addItem("")
        self.cb_v_2.addItem("")
        self.cb_v_2.addItem("")
        self.cb_v_2.addItem("")
        self.cb_v_2.setObjectName(u"cb_v_2")
        self.cb_v_2.setEnabled(True)
        self.cb_v_2.setGeometry(QRect(142, 190, 80, 35))
        font3 = QFont()
        font3.setFamilies([u"Consolas"])
        font3.setPointSize(14)
        self.cb_v_2.setFont(font3)
        self.cb_v_2.setCursor(QCursor(Qt.PointingHandCursor))
        self.cb_v_2.setMaxVisibleItems(11)
        self.cb_v_4 = QComboBox(self.centralwidget)
        self.cb_v_4.addItem("")
        self.cb_v_4.addItem("")
        self.cb_v_4.addItem("")
        self.cb_v_4.addItem("")
        self.cb_v_4.addItem("")
        self.cb_v_4.addItem("")
        self.cb_v_4.addItem("")
        self.cb_v_4.addItem("")
        self.cb_v_4.addItem("")
        self.cb_v_4.addItem("")
        self.cb_v_4.addItem("")
        self.cb_v_4.setObjectName(u"cb_v_4")
        self.cb_v_4.setEnabled(True)
        self.cb_v_4.setGeometry(QRect(307, 190, 80, 35))
        self.cb_v_4.setFont(font3)
        self.cb_v_4.setCursor(QCursor(Qt.PointingHandCursor))
        self.cb_v_4.setMaxVisibleItems(11)
        self.cb_s_6 = QComboBox(self.centralwidget)
        self.cb_s_6.addItem("")
        self.cb_s_6.addItem("")
        self.cb_s_6.addItem("")
        self.cb_s_6.addItem("")
        self.cb_s_6.addItem("")
        self.cb_s_6.addItem("")
        self.cb_s_6.addItem("")
        self.cb_s_6.addItem("")
        self.cb_s_6.addItem("")
        self.cb_s_6.addItem("")
        self.cb_s_6.addItem("")
        self.cb_s_6.setObjectName(u"cb_s_6")
        self.cb_s_6.setEnabled(True)
        self.cb_s_6.setGeometry(QRect(473, 107, 80, 35))
        self.cb_s_6.setFont(font3)
        self.cb_s_6.setCursor(QCursor(Qt.PointingHandCursor))
        self.cb_s_6.setMaxVisibleItems(11)
        self.cb_s_5 = QComboBox(self.centralwidget)
        self.cb_s_5.addItem("")
        self.cb_s_5.addItem("")
        self.cb_s_5.addItem("")
        self.cb_s_5.addItem("")
        self.cb_s_5.addItem("")
        self.cb_s_5.addItem("")
        self.cb_s_5.addItem("")
        self.cb_s_5.addItem("")
        self.cb_s_5.addItem("")
        self.cb_s_5.addItem("")
        self.cb_s_5.addItem("")
        self.cb_s_5.setObjectName(u"cb_s_5")
        self.cb_s_5.setEnabled(True)
        self.cb_s_5.setGeometry(QRect(390, 107, 80, 35))
        self.cb_s_5.setFont(font3)
        self.cb_s_5.setCursor(QCursor(Qt.PointingHandCursor))
        self.cb_s_5.setMaxVisibleItems(11)
        self.cb_f_4 = QComboBox(self.centralwidget)
        self.cb_f_4.addItem("")
        self.cb_f_4.addItem("")
        self.cb_f_4.addItem("")
        self.cb_f_4.addItem("")
        self.cb_f_4.addItem("")
        self.cb_f_4.addItem("")
        self.cb_f_4.addItem("")
        self.cb_f_4.addItem("")
        self.cb_f_4.addItem("")
        self.cb_f_4.addItem("")
        self.cb_f_4.addItem("")
        self.cb_f_4.setObjectName(u"cb_f_4")
        self.cb_f_4.setEnabled(True)
        self.cb_f_4.setGeometry(QRect(307, 149, 80, 35))
        self.cb_f_4.setFont(font3)
        self.cb_f_4.setCursor(QCursor(Qt.PointingHandCursor))
        self.cb_f_4.setMaxVisibleItems(11)
        self.cb_s_2 = QComboBox(self.centralwidget)
        self.cb_s_2.addItem("")
        self.cb_s_2.addItem("")
        self.cb_s_2.addItem("")
        self.cb_s_2.addItem("")
        self.cb_s_2.addItem("")
        self.cb_s_2.addItem("")
        self.cb_s_2.addItem("")
        self.cb_s_2.addItem("")
        self.cb_s_2.addItem("")
        self.cb_s_2.addItem("")
        self.cb_s_2.addItem("")
        self.cb_s_2.setObjectName(u"cb_s_2")
        self.cb_s_2.setEnabled(True)
        self.cb_s_2.setGeometry(QRect(142, 107, 80, 35))
        self.cb_s_2.setFont(font3)
        self.cb_s_2.setCursor(QCursor(Qt.PointingHandCursor))
        self.cb_s_2.setMaxVisibleItems(11)
        self.cb_f_1 = QComboBox(self.centralwidget)
        self.cb_f_1.addItem("")
        self.cb_f_1.addItem("")
        self.cb_f_1.addItem("")
        self.cb_f_1.addItem("")
        self.cb_f_1.addItem("")
        self.cb_f_1.addItem("")
        self.cb_f_1.addItem("")
        self.cb_f_1.addItem("")
        self.cb_f_1.addItem("")
        self.cb_f_1.addItem("")
        self.cb_f_1.addItem("")
        self.cb_f_1.setObjectName(u"cb_f_1")
        self.cb_f_1.setEnabled(True)
        self.cb_f_1.setGeometry(QRect(59, 149, 80, 35))
        self.cb_f_1.setFont(font3)
        self.cb_f_1.setCursor(QCursor(Qt.PointingHandCursor))
        self.cb_f_1.setMaxVisibleItems(11)
        self.cb_m_1 = QComboBox(self.centralwidget)
        self.cb_m_1.addItem("")
        self.cb_m_1.addItem("")
        self.cb_m_1.addItem("")
        self.cb_m_1.addItem("")
        self.cb_m_1.addItem("")
        self.cb_m_1.addItem("")
        self.cb_m_1.addItem("")
        self.cb_m_1.addItem("")
        self.cb_m_1.addItem("")
        self.cb_m_1.addItem("")
        self.cb_m_1.addItem("")
        self.cb_m_1.setObjectName(u"cb_m_1")
        self.cb_m_1.setEnabled(True)
        self.cb_m_1.setGeometry(QRect(59, 65, 80, 35))
        self.cb_m_1.setFont(font3)
        self.cb_m_1.setCursor(QCursor(Qt.PointingHandCursor))
        self.cb_m_1.setEditable(False)
        self.cb_m_1.setMaxVisibleItems(11)
        self.cb_s_3 = QComboBox(self.centralwidget)
        self.cb_s_3.addItem("")
        self.cb_s_3.addItem("")
        self.cb_s_3.addItem("")
        self.cb_s_3.addItem("")
        self.cb_s_3.addItem("")
        self.cb_s_3.addItem("")
        self.cb_s_3.addItem("")
        self.cb_s_3.addItem("")
        self.cb_s_3.addItem("")
        self.cb_s_3.addItem("")
        self.cb_s_3.addItem("")
        self.cb_s_3.setObjectName(u"cb_s_3")
        self.cb_s_3.setEnabled(True)
        self.cb_s_3.setGeometry(QRect(225, 107, 79, 35))
        self.cb_s_3.setFont(font3)
        self.cb_s_3.setCursor(QCursor(Qt.PointingHandCursor))
        self.cb_s_3.setMaxVisibleItems(11)
        self.cb_v_5 = QComboBox(self.centralwidget)
        self.cb_v_5.addItem("")
        self.cb_v_5.addItem("")
        self.cb_v_5.addItem("")
        self.cb_v_5.addItem("")
        self.cb_v_5.addItem("")
        self.cb_v_5.addItem("")
        self.cb_v_5.addItem("")
        self.cb_v_5.addItem("")
        self.cb_v_5.addItem("")
        self.cb_v_5.addItem("")
        self.cb_v_5.addItem("")
        self.cb_v_5.setObjectName(u"cb_v_5")
        self.cb_v_5.setEnabled(True)
        self.cb_v_5.setGeometry(QRect(390, 190, 80, 35))
        self.cb_v_5.setFont(font3)
        self.cb_v_5.setCursor(QCursor(Qt.PointingHandCursor))
        self.cb_v_5.setMaxVisibleItems(11)
        self.cb_m_5 = QComboBox(self.centralwidget)
        self.cb_m_5.addItem("")
        self.cb_m_5.addItem("")
        self.cb_m_5.addItem("")
        self.cb_m_5.addItem("")
        self.cb_m_5.addItem("")
        self.cb_m_5.addItem("")
        self.cb_m_5.addItem("")
        self.cb_m_5.addItem("")
        self.cb_m_5.addItem("")
        self.cb_m_5.addItem("")
        self.cb_m_5.addItem("")
        self.cb_m_5.setObjectName(u"cb_m_5")
        self.cb_m_5.setEnabled(True)
        self.cb_m_5.setGeometry(QRect(390, 65, 80, 35))
        self.cb_m_5.setFont(font3)
        self.cb_m_5.setCursor(QCursor(Qt.PointingHandCursor))
        self.cb_m_5.setMaxVisibleItems(11)
        self.cb_f_5 = QComboBox(self.centralwidget)
        self.cb_f_5.addItem("")
        self.cb_f_5.addItem("")
        self.cb_f_5.addItem("")
        self.cb_f_5.addItem("")
        self.cb_f_5.addItem("")
        self.cb_f_5.addItem("")
        self.cb_f_5.addItem("")
        self.cb_f_5.addItem("")
        self.cb_f_5.addItem("")
        self.cb_f_5.addItem("")
        self.cb_f_5.addItem("")
        self.cb_f_5.setObjectName(u"cb_f_5")
        self.cb_f_5.setEnabled(True)
        self.cb_f_5.setGeometry(QRect(390, 149, 80, 35))
        self.cb_f_5.setFont(font3)
        self.cb_f_5.setCursor(QCursor(Qt.PointingHandCursor))
        self.cb_f_5.setMaxVisibleItems(11)
        self.cb_f_3 = QComboBox(self.centralwidget)
        self.cb_f_3.addItem("")
        self.cb_f_3.addItem("")
        self.cb_f_3.addItem("")
        self.cb_f_3.addItem("")
        self.cb_f_3.addItem("")
        self.cb_f_3.addItem("")
        self.cb_f_3.addItem("")
        self.cb_f_3.addItem("")
        self.cb_f_3.addItem("")
        self.cb_f_3.addItem("")
        self.cb_f_3.addItem("")
        self.cb_f_3.setObjectName(u"cb_f_3")
        self.cb_f_3.setEnabled(True)
        self.cb_f_3.setGeometry(QRect(225, 149, 79, 35))
        self.cb_f_3.setFont(font3)
        self.cb_f_3.setCursor(QCursor(Qt.PointingHandCursor))
        self.cb_f_3.setMaxVisibleItems(11)
        self.cb_s_1 = QComboBox(self.centralwidget)
        self.cb_s_1.addItem("")
        self.cb_s_1.addItem("")
        self.cb_s_1.addItem("")
        self.cb_s_1.addItem("")
        self.cb_s_1.addItem("")
        self.cb_s_1.addItem("")
        self.cb_s_1.addItem("")
        self.cb_s_1.addItem("")
        self.cb_s_1.addItem("")
        self.cb_s_1.addItem("")
        self.cb_s_1.addItem("")
        self.cb_s_1.setObjectName(u"cb_s_1")
        self.cb_s_1.setEnabled(True)
        self.cb_s_1.setGeometry(QRect(59, 107, 80, 35))
        self.cb_s_1.setFont(font3)
        self.cb_s_1.setCursor(QCursor(Qt.PointingHandCursor))
        self.cb_s_1.setMaxVisibleItems(11)
        self.cb_v_6 = QComboBox(self.centralwidget)
        self.cb_v_6.addItem("")
        self.cb_v_6.addItem("")
        self.cb_v_6.addItem("")
        self.cb_v_6.addItem("")
        self.cb_v_6.addItem("")
        self.cb_v_6.addItem("")
        self.cb_v_6.addItem("")
        self.cb_v_6.addItem("")
        self.cb_v_6.addItem("")
        self.cb_v_6.addItem("")
        self.cb_v_6.addItem("")
        self.cb_v_6.setObjectName(u"cb_v_6")
        self.cb_v_6.setEnabled(True)
        self.cb_v_6.setGeometry(QRect(473, 190, 80, 35))
        font4 = QFont()
        font4.setFamilies([u"Consolas"])
        font4.setPointSize(14)
        font4.setBold(True)
        self.cb_v_6.setFont(font4)
        self.cb_v_6.setCursor(QCursor(Qt.PointingHandCursor))
        self.cb_v_6.setMaxVisibleItems(11)
        self.cb_m_6 = QComboBox(self.centralwidget)
        self.cb_m_6.addItem("")
        self.cb_m_6.addItem("")
        self.cb_m_6.addItem("")
        self.cb_m_6.addItem("")
        self.cb_m_6.addItem("")
        self.cb_m_6.addItem("")
        self.cb_m_6.addItem("")
        self.cb_m_6.addItem("")
        self.cb_m_6.addItem("")
        self.cb_m_6.addItem("")
        self.cb_m_6.addItem("")
        self.cb_m_6.setObjectName(u"cb_m_6")
        self.cb_m_6.setEnabled(True)
        self.cb_m_6.setGeometry(QRect(473, 65, 80, 35))
        self.cb_m_6.setFont(font3)
        self.cb_m_6.setCursor(QCursor(Qt.PointingHandCursor))
        self.cb_m_6.setMaxVisibleItems(11)
        self.cb_f_2 = QComboBox(self.centralwidget)
        self.cb_f_2.addItem("")
        self.cb_f_2.addItem("")
        self.cb_f_2.addItem("")
        self.cb_f_2.addItem("")
        self.cb_f_2.addItem("")
        self.cb_f_2.addItem("")
        self.cb_f_2.addItem("")
        self.cb_f_2.addItem("")
        self.cb_f_2.addItem("")
        self.cb_f_2.addItem("")
        self.cb_f_2.addItem("")
        self.cb_f_2.setObjectName(u"cb_f_2")
        self.cb_f_2.setEnabled(True)
        self.cb_f_2.setGeometry(QRect(142, 149, 80, 35))
        self.cb_f_2.setFont(font3)
        self.cb_f_2.setCursor(QCursor(Qt.PointingHandCursor))
        self.cb_f_2.setMaxVisibleItems(11)
        self.cb_f_6 = QComboBox(self.centralwidget)
        self.cb_f_6.addItem("")
        self.cb_f_6.addItem("")
        self.cb_f_6.addItem("")
        self.cb_f_6.addItem("")
        self.cb_f_6.addItem("")
        self.cb_f_6.addItem("")
        self.cb_f_6.addItem("")
        self.cb_f_6.addItem("")
        self.cb_f_6.addItem("")
        self.cb_f_6.addItem("")
        self.cb_f_6.addItem("")
        self.cb_f_6.setObjectName(u"cb_f_6")
        self.cb_f_6.setEnabled(True)
        self.cb_f_6.setGeometry(QRect(473, 149, 80, 35))
        self.cb_f_6.setFont(font3)
        self.cb_f_6.setCursor(QCursor(Qt.PointingHandCursor))
        self.cb_f_6.setEditable(False)
        self.cb_f_6.setMaxVisibleItems(11)
        self.cb_m_2 = QComboBox(self.centralwidget)
        self.cb_m_2.addItem("")
        self.cb_m_2.addItem("")
        self.cb_m_2.addItem("")
        self.cb_m_2.addItem("")
        self.cb_m_2.addItem("")
        self.cb_m_2.addItem("")
        self.cb_m_2.addItem("")
        self.cb_m_2.addItem("")
        self.cb_m_2.addItem("")
        self.cb_m_2.addItem("")
        self.cb_m_2.addItem("")
        self.cb_m_2.setObjectName(u"cb_m_2")
        self.cb_m_2.setEnabled(True)
        self.cb_m_2.setGeometry(QRect(142, 65, 80, 35))
        self.cb_m_2.setFont(font3)
        self.cb_m_2.setCursor(QCursor(Qt.PointingHandCursor))
        self.cb_m_2.setMaxVisibleItems(11)
        self.cb_m_4 = QComboBox(self.centralwidget)
        self.cb_m_4.addItem("")
        self.cb_m_4.addItem("")
        self.cb_m_4.addItem("")
        self.cb_m_4.addItem("")
        self.cb_m_4.addItem("")
        self.cb_m_4.addItem("")
        self.cb_m_4.addItem("")
        self.cb_m_4.addItem("")
        self.cb_m_4.addItem("")
        self.cb_m_4.addItem("")
        self.cb_m_4.addItem("")
        self.cb_m_4.setObjectName(u"cb_m_4")
        self.cb_m_4.setEnabled(True)
        self.cb_m_4.setGeometry(QRect(307, 65, 80, 35))
        self.cb_m_4.setFont(font3)
        self.cb_m_4.setCursor(QCursor(Qt.PointingHandCursor))
        self.cb_m_4.setMaxVisibleItems(11)
        self.cb_m_3 = QComboBox(self.centralwidget)
        self.cb_m_3.addItem("")
        self.cb_m_3.addItem("")
        self.cb_m_3.addItem("")
        self.cb_m_3.addItem("")
        self.cb_m_3.addItem("")
        self.cb_m_3.addItem("")
        self.cb_m_3.addItem("")
        self.cb_m_3.addItem("")
        self.cb_m_3.addItem("")
        self.cb_m_3.addItem("")
        self.cb_m_3.addItem("")
        self.cb_m_3.setObjectName(u"cb_m_3")
        self.cb_m_3.setEnabled(True)
        self.cb_m_3.setGeometry(QRect(225, 65, 79, 35))
        self.cb_m_3.setFont(font3)
        self.cb_m_3.setCursor(QCursor(Qt.PointingHandCursor))
        self.cb_m_3.setMaxVisibleItems(11)
        self.cb_v_3 = QComboBox(self.centralwidget)
        self.cb_v_3.addItem("")
        self.cb_v_3.addItem("")
        self.cb_v_3.addItem("")
        self.cb_v_3.addItem("")
        self.cb_v_3.addItem("")
        self.cb_v_3.addItem("")
        self.cb_v_3.addItem("")
        self.cb_v_3.addItem("")
        self.cb_v_3.addItem("")
        self.cb_v_3.addItem("")
        self.cb_v_3.addItem("")
        self.cb_v_3.setObjectName(u"cb_v_3")
        self.cb_v_3.setEnabled(True)
        self.cb_v_3.setGeometry(QRect(225, 190, 79, 35))
        self.cb_v_3.setFont(font3)
        self.cb_v_3.setCursor(QCursor(Qt.PointingHandCursor))
        self.cb_v_3.setMaxVisibleItems(11)
        self.cb_v_1 = QComboBox(self.centralwidget)
        self.cb_v_1.addItem("")
        self.cb_v_1.addItem("")
        self.cb_v_1.addItem("")
        self.cb_v_1.addItem("")
        self.cb_v_1.addItem("")
        self.cb_v_1.addItem("")
        self.cb_v_1.addItem("")
        self.cb_v_1.addItem("")
        self.cb_v_1.addItem("")
        self.cb_v_1.addItem("")
        self.cb_v_1.addItem("")
        self.cb_v_1.setObjectName(u"cb_v_1")
        self.cb_v_1.setEnabled(True)
        self.cb_v_1.setGeometry(QRect(59, 190, 80, 35))
        self.cb_v_1.setFont(font3)
        self.cb_v_1.setCursor(QCursor(Qt.PointingHandCursor))
        self.cb_v_1.setMaxVisibleItems(11)
        self.cb_s_4 = QComboBox(self.centralwidget)
        self.cb_s_4.addItem("")
        self.cb_s_4.addItem("")
        self.cb_s_4.addItem("")
        self.cb_s_4.addItem("")
        self.cb_s_4.addItem("")
        self.cb_s_4.addItem("")
        self.cb_s_4.addItem("")
        self.cb_s_4.addItem("")
        self.cb_s_4.addItem("")
        self.cb_s_4.addItem("")
        self.cb_s_4.addItem("")
        self.cb_s_4.setObjectName(u"cb_s_4")
        self.cb_s_4.setEnabled(True)
        self.cb_s_4.setGeometry(QRect(307, 107, 80, 35))
        self.cb_s_4.setFont(font3)
        self.cb_s_4.setCursor(QCursor(Qt.PointingHandCursor))
        self.cb_s_4.setMaxVisibleItems(11)
        self.sb_tokens = QSpinBox(self.centralwidget)
        self.sb_tokens.setObjectName(u"sb_tokens")
        self.sb_tokens.setGeometry(QRect(679, 45, 101, 41))
        font5 = QFont()
        font5.setPointSize(12)
        self.sb_tokens.setFont(font5)
        self.sb_tokens.setStyleSheet(u"border: none;")
        self.sb_tokens.setAlignment(Qt.AlignCenter)
        self.sb_tokens.setButtonSymbols(QAbstractSpinBox.PlusMinus)
        self.sb_tokens.setProperty("showGroupSeparator", False)
        self.sb_tokens.setMaximum(102600)
        self.lcdWins = QLCDNumber(self.centralwidget)
        self.lcdWins.setObjectName(u"lcdWins")
        self.lcdWins.setGeometry(QRect(713, 200, 70, 23))
        self.lcdWins.setFrameShape(QFrame.Box)
        self.lcdWins.setFrameShadow(QFrame.Raised)
        self.lcdWins.setSmallDecimalPoint(True)
        self.lcdWins.setDigitCount(6)
        self.lcdWins.setMode(QLCDNumber.Dec)
        self.lcdWins.setSegmentStyle(QLCDNumber.Filled)
        self.lcdWins.setProperty("value", 51300.000000000000000)
        self.lcdWins.setProperty("intValue", 51300)
        self.lcdEnd = QLCDNumber(self.centralwidget)
        self.lcdEnd.setObjectName(u"lcdEnd")
        self.lcdEnd.setGeometry(QRect(713, 180, 70, 23))
        self.lcdEnd.setSmallDecimalPoint(True)
        self.lcdEnd.setDigitCount(6)
        self.lcdEnd.setProperty("value", 102600.000000000000000)
        self.lcdTokens = QLCDNumber(self.centralwidget)
        self.lcdTokens.setObjectName(u"lcdTokens")
        self.lcdTokens.setGeometry(QRect(713, 160, 70, 23))
        font6 = QFont()
        font6.setBold(False)
        self.lcdTokens.setFont(font6)
        self.lcdTokens.setSmallDecimalPoint(True)
        self.lcdTokens.setDigitCount(6)
        self.lcdTokens.setProperty("value", 2.000000000000000)
        QFrmMain.setCentralWidget(self.centralwidget)
        self.frame.raise_()
        self.cb_stage.raise_()
        self.label.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.cb_v_2.raise_()
        self.cb_v_4.raise_()
        self.cb_s_6.raise_()
        self.cb_s_5.raise_()
        self.cb_f_4.raise_()
        self.cb_s_2.raise_()
        self.cb_f_1.raise_()
        self.cb_m_1.raise_()
        self.cb_s_3.raise_()
        self.cb_v_5.raise_()
        self.cb_m_5.raise_()
        self.cb_f_5.raise_()
        self.cb_f_3.raise_()
        self.cb_s_1.raise_()
        self.cb_v_6.raise_()
        self.cb_m_6.raise_()
        self.cb_f_2.raise_()
        self.cb_f_6.raise_()
        self.cb_m_2.raise_()
        self.cb_m_4.raise_()
        self.cb_m_3.raise_()
        self.cb_v_3.raise_()
        self.cb_v_1.raise_()
        self.cb_s_4.raise_()
        self.sb_tokens.raise_()
        self.lcdWins.raise_()
        self.lcdEnd.raise_()
        self.lcdTokens.raise_()

        self.retranslateUi(QFrmMain)

        self.cb_m_1.setCurrentIndex(0)
        self.cb_v_6.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(QFrmMain)
    # setupUi

    def retranslateUi(self, QFrmMain):
        QFrmMain.setWindowTitle(QCoreApplication.translate("QFrmMain", u"GHC", None))
        self.actionSave.setText(QCoreApplication.translate("QFrmMain", u"Save", None))
        self.actionLoad.setText(QCoreApplication.translate("QFrmMain", u"Load", None))
        self.actionSettings.setText(QCoreApplication.translate("QFrmMain", u"Settings", None))
        self.cb_stage.setItemText(0, QCoreApplication.translate("QFrmMain", u"1", None))
        self.cb_stage.setItemText(1, QCoreApplication.translate("QFrmMain", u"2", None))
        self.cb_stage.setItemText(2, QCoreApplication.translate("QFrmMain", u"3", None))
        self.cb_stage.setItemText(3, QCoreApplication.translate("QFrmMain", u"4", None))
        self.cb_stage.setItemText(4, QCoreApplication.translate("QFrmMain", u"5", None))

        self.label.setText(QCoreApplication.translate("QFrmMain", u"Stage", None))
        self.label_7.setText(QCoreApplication.translate("QFrmMain", u"Tokens/Win", None))
        self.label_8.setText(QCoreApplication.translate("QFrmMain", u"Tokens/End", None))
        self.label_9.setText(QCoreApplication.translate("QFrmMain", u"Needed Wins", None))
        self.label_10.setText(QCoreApplication.translate("QFrmMain", u"Tokens", None))
        self.cb_v_2.setItemText(0, "")
        self.cb_v_2.setItemText(1, QCoreApplication.translate("QFrmMain", u"1/10", None))
        self.cb_v_2.setItemText(2, QCoreApplication.translate("QFrmMain", u"2/10", None))
        self.cb_v_2.setItemText(3, QCoreApplication.translate("QFrmMain", u"3/10", None))
        self.cb_v_2.setItemText(4, QCoreApplication.translate("QFrmMain", u"4/10", None))
        self.cb_v_2.setItemText(5, QCoreApplication.translate("QFrmMain", u"5/10", None))
        self.cb_v_2.setItemText(6, QCoreApplication.translate("QFrmMain", u"6/10", None))
        self.cb_v_2.setItemText(7, QCoreApplication.translate("QFrmMain", u"7/10", None))
        self.cb_v_2.setItemText(8, QCoreApplication.translate("QFrmMain", u"8/10", None))
        self.cb_v_2.setItemText(9, QCoreApplication.translate("QFrmMain", u"9/10", None))
        self.cb_v_2.setItemText(10, QCoreApplication.translate("QFrmMain", u"10/10", None))

        self.cb_v_4.setItemText(0, "")
        self.cb_v_4.setItemText(1, QCoreApplication.translate("QFrmMain", u"1/10", None))
        self.cb_v_4.setItemText(2, QCoreApplication.translate("QFrmMain", u"2/10", None))
        self.cb_v_4.setItemText(3, QCoreApplication.translate("QFrmMain", u"3/10", None))
        self.cb_v_4.setItemText(4, QCoreApplication.translate("QFrmMain", u"4/10", None))
        self.cb_v_4.setItemText(5, QCoreApplication.translate("QFrmMain", u"5/10", None))
        self.cb_v_4.setItemText(6, QCoreApplication.translate("QFrmMain", u"6/10", None))
        self.cb_v_4.setItemText(7, QCoreApplication.translate("QFrmMain", u"7/10", None))
        self.cb_v_4.setItemText(8, QCoreApplication.translate("QFrmMain", u"8/10", None))
        self.cb_v_4.setItemText(9, QCoreApplication.translate("QFrmMain", u"9/10", None))
        self.cb_v_4.setItemText(10, QCoreApplication.translate("QFrmMain", u"10/10", None))

        self.cb_s_6.setItemText(0, "")
        self.cb_s_6.setItemText(1, QCoreApplication.translate("QFrmMain", u"1/10", None))
        self.cb_s_6.setItemText(2, QCoreApplication.translate("QFrmMain", u"2/10", None))
        self.cb_s_6.setItemText(3, QCoreApplication.translate("QFrmMain", u"3/10", None))
        self.cb_s_6.setItemText(4, QCoreApplication.translate("QFrmMain", u"4/10", None))
        self.cb_s_6.setItemText(5, QCoreApplication.translate("QFrmMain", u"5/10", None))
        self.cb_s_6.setItemText(6, QCoreApplication.translate("QFrmMain", u"6/10", None))
        self.cb_s_6.setItemText(7, QCoreApplication.translate("QFrmMain", u"7/10", None))
        self.cb_s_6.setItemText(8, QCoreApplication.translate("QFrmMain", u"8/10", None))
        self.cb_s_6.setItemText(9, QCoreApplication.translate("QFrmMain", u"9/10", None))
        self.cb_s_6.setItemText(10, QCoreApplication.translate("QFrmMain", u"10/10", None))

        self.cb_s_5.setItemText(0, "")
        self.cb_s_5.setItemText(1, QCoreApplication.translate("QFrmMain", u"1/10", None))
        self.cb_s_5.setItemText(2, QCoreApplication.translate("QFrmMain", u"2/10", None))
        self.cb_s_5.setItemText(3, QCoreApplication.translate("QFrmMain", u"3/10", None))
        self.cb_s_5.setItemText(4, QCoreApplication.translate("QFrmMain", u"4/10", None))
        self.cb_s_5.setItemText(5, QCoreApplication.translate("QFrmMain", u"5/10", None))
        self.cb_s_5.setItemText(6, QCoreApplication.translate("QFrmMain", u"6/10", None))
        self.cb_s_5.setItemText(7, QCoreApplication.translate("QFrmMain", u"7/10", None))
        self.cb_s_5.setItemText(8, QCoreApplication.translate("QFrmMain", u"8/10", None))
        self.cb_s_5.setItemText(9, QCoreApplication.translate("QFrmMain", u"9/10", None))
        self.cb_s_5.setItemText(10, QCoreApplication.translate("QFrmMain", u"10/10", None))

        self.cb_f_4.setItemText(0, "")
        self.cb_f_4.setItemText(1, QCoreApplication.translate("QFrmMain", u"1/10", None))
        self.cb_f_4.setItemText(2, QCoreApplication.translate("QFrmMain", u"2/10", None))
        self.cb_f_4.setItemText(3, QCoreApplication.translate("QFrmMain", u"3/10", None))
        self.cb_f_4.setItemText(4, QCoreApplication.translate("QFrmMain", u"4/10", None))
        self.cb_f_4.setItemText(5, QCoreApplication.translate("QFrmMain", u"5/10", None))
        self.cb_f_4.setItemText(6, QCoreApplication.translate("QFrmMain", u"6/10", None))
        self.cb_f_4.setItemText(7, QCoreApplication.translate("QFrmMain", u"7/10", None))
        self.cb_f_4.setItemText(8, QCoreApplication.translate("QFrmMain", u"8/10", None))
        self.cb_f_4.setItemText(9, QCoreApplication.translate("QFrmMain", u"9/10", None))
        self.cb_f_4.setItemText(10, QCoreApplication.translate("QFrmMain", u"10/10", None))

        self.cb_s_2.setItemText(0, "")
        self.cb_s_2.setItemText(1, QCoreApplication.translate("QFrmMain", u"1/10", None))
        self.cb_s_2.setItemText(2, QCoreApplication.translate("QFrmMain", u"2/10", None))
        self.cb_s_2.setItemText(3, QCoreApplication.translate("QFrmMain", u"3/10", None))
        self.cb_s_2.setItemText(4, QCoreApplication.translate("QFrmMain", u"4/10", None))
        self.cb_s_2.setItemText(5, QCoreApplication.translate("QFrmMain", u"5/10", None))
        self.cb_s_2.setItemText(6, QCoreApplication.translate("QFrmMain", u"6/10", None))
        self.cb_s_2.setItemText(7, QCoreApplication.translate("QFrmMain", u"7/10", None))
        self.cb_s_2.setItemText(8, QCoreApplication.translate("QFrmMain", u"8/10", None))
        self.cb_s_2.setItemText(9, QCoreApplication.translate("QFrmMain", u"9/10", None))
        self.cb_s_2.setItemText(10, QCoreApplication.translate("QFrmMain", u"10/10", None))

        self.cb_f_1.setItemText(0, "")
        self.cb_f_1.setItemText(1, QCoreApplication.translate("QFrmMain", u"1/10", None))
        self.cb_f_1.setItemText(2, QCoreApplication.translate("QFrmMain", u"2/10", None))
        self.cb_f_1.setItemText(3, QCoreApplication.translate("QFrmMain", u"3/10", None))
        self.cb_f_1.setItemText(4, QCoreApplication.translate("QFrmMain", u"4/10", None))
        self.cb_f_1.setItemText(5, QCoreApplication.translate("QFrmMain", u"5/10", None))
        self.cb_f_1.setItemText(6, QCoreApplication.translate("QFrmMain", u"6/10", None))
        self.cb_f_1.setItemText(7, QCoreApplication.translate("QFrmMain", u"7/10", None))
        self.cb_f_1.setItemText(8, QCoreApplication.translate("QFrmMain", u"8/10", None))
        self.cb_f_1.setItemText(9, QCoreApplication.translate("QFrmMain", u"9/10", None))
        self.cb_f_1.setItemText(10, QCoreApplication.translate("QFrmMain", u"10/10", None))

        self.cb_m_1.setItemText(0, "")
        self.cb_m_1.setItemText(1, QCoreApplication.translate("QFrmMain", u"1/10", None))
        self.cb_m_1.setItemText(2, QCoreApplication.translate("QFrmMain", u"2/10", None))
        self.cb_m_1.setItemText(3, QCoreApplication.translate("QFrmMain", u"3/10", None))
        self.cb_m_1.setItemText(4, QCoreApplication.translate("QFrmMain", u"4/10", None))
        self.cb_m_1.setItemText(5, QCoreApplication.translate("QFrmMain", u"5/10", None))
        self.cb_m_1.setItemText(6, QCoreApplication.translate("QFrmMain", u"6/10", None))
        self.cb_m_1.setItemText(7, QCoreApplication.translate("QFrmMain", u"7/10", None))
        self.cb_m_1.setItemText(8, QCoreApplication.translate("QFrmMain", u"8/10", None))
        self.cb_m_1.setItemText(9, QCoreApplication.translate("QFrmMain", u"9/10", None))
        self.cb_m_1.setItemText(10, QCoreApplication.translate("QFrmMain", u"10/10", None))

        self.cb_s_3.setItemText(0, "")
        self.cb_s_3.setItemText(1, QCoreApplication.translate("QFrmMain", u"1/10", None))
        self.cb_s_3.setItemText(2, QCoreApplication.translate("QFrmMain", u"2/10", None))
        self.cb_s_3.setItemText(3, QCoreApplication.translate("QFrmMain", u"3/10", None))
        self.cb_s_3.setItemText(4, QCoreApplication.translate("QFrmMain", u"4/10", None))
        self.cb_s_3.setItemText(5, QCoreApplication.translate("QFrmMain", u"5/10", None))
        self.cb_s_3.setItemText(6, QCoreApplication.translate("QFrmMain", u"6/10", None))
        self.cb_s_3.setItemText(7, QCoreApplication.translate("QFrmMain", u"7/10", None))
        self.cb_s_3.setItemText(8, QCoreApplication.translate("QFrmMain", u"8/10", None))
        self.cb_s_3.setItemText(9, QCoreApplication.translate("QFrmMain", u"9/10", None))
        self.cb_s_3.setItemText(10, QCoreApplication.translate("QFrmMain", u"10/10", None))

        self.cb_v_5.setItemText(0, "")
        self.cb_v_5.setItemText(1, QCoreApplication.translate("QFrmMain", u"1/10", None))
        self.cb_v_5.setItemText(2, QCoreApplication.translate("QFrmMain", u"2/10", None))
        self.cb_v_5.setItemText(3, QCoreApplication.translate("QFrmMain", u"3/10", None))
        self.cb_v_5.setItemText(4, QCoreApplication.translate("QFrmMain", u"4/10", None))
        self.cb_v_5.setItemText(5, QCoreApplication.translate("QFrmMain", u"5/10", None))
        self.cb_v_5.setItemText(6, QCoreApplication.translate("QFrmMain", u"6/10", None))
        self.cb_v_5.setItemText(7, QCoreApplication.translate("QFrmMain", u"7/10", None))
        self.cb_v_5.setItemText(8, QCoreApplication.translate("QFrmMain", u"8/10", None))
        self.cb_v_5.setItemText(9, QCoreApplication.translate("QFrmMain", u"9/10", None))
        self.cb_v_5.setItemText(10, QCoreApplication.translate("QFrmMain", u"10/10", None))

        self.cb_m_5.setItemText(0, "")
        self.cb_m_5.setItemText(1, QCoreApplication.translate("QFrmMain", u"1/10", None))
        self.cb_m_5.setItemText(2, QCoreApplication.translate("QFrmMain", u"2/10", None))
        self.cb_m_5.setItemText(3, QCoreApplication.translate("QFrmMain", u"3/10", None))
        self.cb_m_5.setItemText(4, QCoreApplication.translate("QFrmMain", u"4/10", None))
        self.cb_m_5.setItemText(5, QCoreApplication.translate("QFrmMain", u"5/10", None))
        self.cb_m_5.setItemText(6, QCoreApplication.translate("QFrmMain", u"6/10", None))
        self.cb_m_5.setItemText(7, QCoreApplication.translate("QFrmMain", u"7/10", None))
        self.cb_m_5.setItemText(8, QCoreApplication.translate("QFrmMain", u"8/10", None))
        self.cb_m_5.setItemText(9, QCoreApplication.translate("QFrmMain", u"9/10", None))
        self.cb_m_5.setItemText(10, QCoreApplication.translate("QFrmMain", u"10/10", None))

        self.cb_f_5.setItemText(0, "")
        self.cb_f_5.setItemText(1, QCoreApplication.translate("QFrmMain", u"1/10", None))
        self.cb_f_5.setItemText(2, QCoreApplication.translate("QFrmMain", u"2/10", None))
        self.cb_f_5.setItemText(3, QCoreApplication.translate("QFrmMain", u"3/10", None))
        self.cb_f_5.setItemText(4, QCoreApplication.translate("QFrmMain", u"4/10", None))
        self.cb_f_5.setItemText(5, QCoreApplication.translate("QFrmMain", u"5/10", None))
        self.cb_f_5.setItemText(6, QCoreApplication.translate("QFrmMain", u"6/10", None))
        self.cb_f_5.setItemText(7, QCoreApplication.translate("QFrmMain", u"7/10", None))
        self.cb_f_5.setItemText(8, QCoreApplication.translate("QFrmMain", u"8/10", None))
        self.cb_f_5.setItemText(9, QCoreApplication.translate("QFrmMain", u"9/10", None))
        self.cb_f_5.setItemText(10, QCoreApplication.translate("QFrmMain", u"10/10", None))

        self.cb_f_3.setItemText(0, "")
        self.cb_f_3.setItemText(1, QCoreApplication.translate("QFrmMain", u"1/10", None))
        self.cb_f_3.setItemText(2, QCoreApplication.translate("QFrmMain", u"2/10", None))
        self.cb_f_3.setItemText(3, QCoreApplication.translate("QFrmMain", u"3/10", None))
        self.cb_f_3.setItemText(4, QCoreApplication.translate("QFrmMain", u"4/10", None))
        self.cb_f_3.setItemText(5, QCoreApplication.translate("QFrmMain", u"5/10", None))
        self.cb_f_3.setItemText(6, QCoreApplication.translate("QFrmMain", u"6/10", None))
        self.cb_f_3.setItemText(7, QCoreApplication.translate("QFrmMain", u"7/10", None))
        self.cb_f_3.setItemText(8, QCoreApplication.translate("QFrmMain", u"8/10", None))
        self.cb_f_3.setItemText(9, QCoreApplication.translate("QFrmMain", u"9/10", None))
        self.cb_f_3.setItemText(10, QCoreApplication.translate("QFrmMain", u"10/10", None))

        self.cb_s_1.setItemText(0, "")
        self.cb_s_1.setItemText(1, QCoreApplication.translate("QFrmMain", u"1/10", None))
        self.cb_s_1.setItemText(2, QCoreApplication.translate("QFrmMain", u"2/10", None))
        self.cb_s_1.setItemText(3, QCoreApplication.translate("QFrmMain", u"3/10", None))
        self.cb_s_1.setItemText(4, QCoreApplication.translate("QFrmMain", u"4/10", None))
        self.cb_s_1.setItemText(5, QCoreApplication.translate("QFrmMain", u"5/10", None))
        self.cb_s_1.setItemText(6, QCoreApplication.translate("QFrmMain", u"6/10", None))
        self.cb_s_1.setItemText(7, QCoreApplication.translate("QFrmMain", u"7/10", None))
        self.cb_s_1.setItemText(8, QCoreApplication.translate("QFrmMain", u"8/10", None))
        self.cb_s_1.setItemText(9, QCoreApplication.translate("QFrmMain", u"9/10", None))
        self.cb_s_1.setItemText(10, QCoreApplication.translate("QFrmMain", u"10/10", None))

        self.cb_v_6.setItemText(0, "")
        self.cb_v_6.setItemText(1, QCoreApplication.translate("QFrmMain", u"1/10", None))
        self.cb_v_6.setItemText(2, QCoreApplication.translate("QFrmMain", u"2/10", None))
        self.cb_v_6.setItemText(3, QCoreApplication.translate("QFrmMain", u"3/10", None))
        self.cb_v_6.setItemText(4, QCoreApplication.translate("QFrmMain", u"4/10", None))
        self.cb_v_6.setItemText(5, QCoreApplication.translate("QFrmMain", u"5/10", None))
        self.cb_v_6.setItemText(6, QCoreApplication.translate("QFrmMain", u"6/10", None))
        self.cb_v_6.setItemText(7, QCoreApplication.translate("QFrmMain", u"7/10", None))
        self.cb_v_6.setItemText(8, QCoreApplication.translate("QFrmMain", u"8/10", None))
        self.cb_v_6.setItemText(9, QCoreApplication.translate("QFrmMain", u"9/10", None))
        self.cb_v_6.setItemText(10, QCoreApplication.translate("QFrmMain", u"10/10", None))

        self.cb_m_6.setItemText(0, "")
        self.cb_m_6.setItemText(1, QCoreApplication.translate("QFrmMain", u"1/10", None))
        self.cb_m_6.setItemText(2, QCoreApplication.translate("QFrmMain", u"2/10", None))
        self.cb_m_6.setItemText(3, QCoreApplication.translate("QFrmMain", u"3/10", None))
        self.cb_m_6.setItemText(4, QCoreApplication.translate("QFrmMain", u"4/10", None))
        self.cb_m_6.setItemText(5, QCoreApplication.translate("QFrmMain", u"5/10", None))
        self.cb_m_6.setItemText(6, QCoreApplication.translate("QFrmMain", u"6/10", None))
        self.cb_m_6.setItemText(7, QCoreApplication.translate("QFrmMain", u"7/10", None))
        self.cb_m_6.setItemText(8, QCoreApplication.translate("QFrmMain", u"8/10", None))
        self.cb_m_6.setItemText(9, QCoreApplication.translate("QFrmMain", u"9/10", None))
        self.cb_m_6.setItemText(10, QCoreApplication.translate("QFrmMain", u"10/10", None))

        self.cb_f_2.setItemText(0, "")
        self.cb_f_2.setItemText(1, QCoreApplication.translate("QFrmMain", u"1/10", None))
        self.cb_f_2.setItemText(2, QCoreApplication.translate("QFrmMain", u"2/10", None))
        self.cb_f_2.setItemText(3, QCoreApplication.translate("QFrmMain", u"3/10", None))
        self.cb_f_2.setItemText(4, QCoreApplication.translate("QFrmMain", u"4/10", None))
        self.cb_f_2.setItemText(5, QCoreApplication.translate("QFrmMain", u"5/10", None))
        self.cb_f_2.setItemText(6, QCoreApplication.translate("QFrmMain", u"6/10", None))
        self.cb_f_2.setItemText(7, QCoreApplication.translate("QFrmMain", u"7/10", None))
        self.cb_f_2.setItemText(8, QCoreApplication.translate("QFrmMain", u"8/10", None))
        self.cb_f_2.setItemText(9, QCoreApplication.translate("QFrmMain", u"9/10", None))
        self.cb_f_2.setItemText(10, QCoreApplication.translate("QFrmMain", u"10/10", None))

        self.cb_f_6.setItemText(0, "")
        self.cb_f_6.setItemText(1, QCoreApplication.translate("QFrmMain", u"1/10", None))
        self.cb_f_6.setItemText(2, QCoreApplication.translate("QFrmMain", u"2/10", None))
        self.cb_f_6.setItemText(3, QCoreApplication.translate("QFrmMain", u"3/10", None))
        self.cb_f_6.setItemText(4, QCoreApplication.translate("QFrmMain", u"4/10", None))
        self.cb_f_6.setItemText(5, QCoreApplication.translate("QFrmMain", u"5/10", None))
        self.cb_f_6.setItemText(6, QCoreApplication.translate("QFrmMain", u"6/10", None))
        self.cb_f_6.setItemText(7, QCoreApplication.translate("QFrmMain", u"7/10", None))
        self.cb_f_6.setItemText(8, QCoreApplication.translate("QFrmMain", u"8/10", None))
        self.cb_f_6.setItemText(9, QCoreApplication.translate("QFrmMain", u"9/10", None))
        self.cb_f_6.setItemText(10, QCoreApplication.translate("QFrmMain", u"10/10", None))

        self.cb_m_2.setItemText(0, "")
        self.cb_m_2.setItemText(1, QCoreApplication.translate("QFrmMain", u"1/10", None))
        self.cb_m_2.setItemText(2, QCoreApplication.translate("QFrmMain", u"2/10", None))
        self.cb_m_2.setItemText(3, QCoreApplication.translate("QFrmMain", u"3/10", None))
        self.cb_m_2.setItemText(4, QCoreApplication.translate("QFrmMain", u"4/10", None))
        self.cb_m_2.setItemText(5, QCoreApplication.translate("QFrmMain", u"5/10", None))
        self.cb_m_2.setItemText(6, QCoreApplication.translate("QFrmMain", u"6/10", None))
        self.cb_m_2.setItemText(7, QCoreApplication.translate("QFrmMain", u"7/10", None))
        self.cb_m_2.setItemText(8, QCoreApplication.translate("QFrmMain", u"8/10", None))
        self.cb_m_2.setItemText(9, QCoreApplication.translate("QFrmMain", u"9/10", None))
        self.cb_m_2.setItemText(10, QCoreApplication.translate("QFrmMain", u"10/10", None))

        self.cb_m_4.setItemText(0, "")
        self.cb_m_4.setItemText(1, QCoreApplication.translate("QFrmMain", u"1/10", None))
        self.cb_m_4.setItemText(2, QCoreApplication.translate("QFrmMain", u"2/10", None))
        self.cb_m_4.setItemText(3, QCoreApplication.translate("QFrmMain", u"3/10", None))
        self.cb_m_4.setItemText(4, QCoreApplication.translate("QFrmMain", u"4/10", None))
        self.cb_m_4.setItemText(5, QCoreApplication.translate("QFrmMain", u"5/10", None))
        self.cb_m_4.setItemText(6, QCoreApplication.translate("QFrmMain", u"6/10", None))
        self.cb_m_4.setItemText(7, QCoreApplication.translate("QFrmMain", u"7/10", None))
        self.cb_m_4.setItemText(8, QCoreApplication.translate("QFrmMain", u"8/10", None))
        self.cb_m_4.setItemText(9, QCoreApplication.translate("QFrmMain", u"9/10", None))
        self.cb_m_4.setItemText(10, QCoreApplication.translate("QFrmMain", u"10/10", None))

        self.cb_m_3.setItemText(0, "")
        self.cb_m_3.setItemText(1, QCoreApplication.translate("QFrmMain", u"1/10", None))
        self.cb_m_3.setItemText(2, QCoreApplication.translate("QFrmMain", u"2/10", None))
        self.cb_m_3.setItemText(3, QCoreApplication.translate("QFrmMain", u"3/10", None))
        self.cb_m_3.setItemText(4, QCoreApplication.translate("QFrmMain", u"4/10", None))
        self.cb_m_3.setItemText(5, QCoreApplication.translate("QFrmMain", u"5/10", None))
        self.cb_m_3.setItemText(6, QCoreApplication.translate("QFrmMain", u"6/10", None))
        self.cb_m_3.setItemText(7, QCoreApplication.translate("QFrmMain", u"7/10", None))
        self.cb_m_3.setItemText(8, QCoreApplication.translate("QFrmMain", u"8/10", None))
        self.cb_m_3.setItemText(9, QCoreApplication.translate("QFrmMain", u"9/10", None))
        self.cb_m_3.setItemText(10, QCoreApplication.translate("QFrmMain", u"10/10", None))

        self.cb_v_3.setItemText(0, "")
        self.cb_v_3.setItemText(1, QCoreApplication.translate("QFrmMain", u"1/10", None))
        self.cb_v_3.setItemText(2, QCoreApplication.translate("QFrmMain", u"2/10", None))
        self.cb_v_3.setItemText(3, QCoreApplication.translate("QFrmMain", u"3/10", None))
        self.cb_v_3.setItemText(4, QCoreApplication.translate("QFrmMain", u"4/10", None))
        self.cb_v_3.setItemText(5, QCoreApplication.translate("QFrmMain", u"5/10", None))
        self.cb_v_3.setItemText(6, QCoreApplication.translate("QFrmMain", u"6/10", None))
        self.cb_v_3.setItemText(7, QCoreApplication.translate("QFrmMain", u"7/10", None))
        self.cb_v_3.setItemText(8, QCoreApplication.translate("QFrmMain", u"8/10", None))
        self.cb_v_3.setItemText(9, QCoreApplication.translate("QFrmMain", u"9/10", None))
        self.cb_v_3.setItemText(10, QCoreApplication.translate("QFrmMain", u"10/10", None))

        self.cb_v_1.setItemText(0, "")
        self.cb_v_1.setItemText(1, QCoreApplication.translate("QFrmMain", u"1/10", None))
        self.cb_v_1.setItemText(2, QCoreApplication.translate("QFrmMain", u"2/10", None))
        self.cb_v_1.setItemText(3, QCoreApplication.translate("QFrmMain", u"3/10", None))
        self.cb_v_1.setItemText(4, QCoreApplication.translate("QFrmMain", u"4/10", None))
        self.cb_v_1.setItemText(5, QCoreApplication.translate("QFrmMain", u"5/10", None))
        self.cb_v_1.setItemText(6, QCoreApplication.translate("QFrmMain", u"6/10", None))
        self.cb_v_1.setItemText(7, QCoreApplication.translate("QFrmMain", u"7/10", None))
        self.cb_v_1.setItemText(8, QCoreApplication.translate("QFrmMain", u"8/10", None))
        self.cb_v_1.setItemText(9, QCoreApplication.translate("QFrmMain", u"9/10", None))
        self.cb_v_1.setItemText(10, QCoreApplication.translate("QFrmMain", u"10/10", None))

        self.cb_s_4.setItemText(0, "")
        self.cb_s_4.setItemText(1, QCoreApplication.translate("QFrmMain", u"1/10", None))
        self.cb_s_4.setItemText(2, QCoreApplication.translate("QFrmMain", u"2/10", None))
        self.cb_s_4.setItemText(3, QCoreApplication.translate("QFrmMain", u"3/10", None))
        self.cb_s_4.setItemText(4, QCoreApplication.translate("QFrmMain", u"4/10", None))
        self.cb_s_4.setItemText(5, QCoreApplication.translate("QFrmMain", u"5/10", None))
        self.cb_s_4.setItemText(6, QCoreApplication.translate("QFrmMain", u"6/10", None))
        self.cb_s_4.setItemText(7, QCoreApplication.translate("QFrmMain", u"7/10", None))
        self.cb_s_4.setItemText(8, QCoreApplication.translate("QFrmMain", u"8/10", None))
        self.cb_s_4.setItemText(9, QCoreApplication.translate("QFrmMain", u"9/10", None))
        self.cb_s_4.setItemText(10, QCoreApplication.translate("QFrmMain", u"10/10", None))

    # retranslateUi

